# Generated by Django 4.2 on 2024-04-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='costumer_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='costumer_name',
            new_name='customer_name',
        ),
    ]
