# Generated by Django 4.2 on 2024-04-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_costumer_email_contactform_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flan',
            old_name='descriptiorn',
            new_name='description',
        ),
    ]
